# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.qiuyuhome.com
date_format: "ordinal"
title: QiuYu Blog
subtitle: "The record bit by bit, are the mark of my growth"
description: "邱宇的个人博客"
keywords: 邱宇, QiuYu, qiuyu, PHP, 技术博客, linux, 邱宇博客
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: QiuYu
organization: zjmedia, Inc.
organization_url: https://www.zjmedia.com
location: Beijing, China
email: 530004000@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /QA/
    label: Q&A

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: links

  -
    href: /about/
    label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: qiuyuhome/qiuyuhome.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: qiuyuhome
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: qiuyuhome
    repo: blog-comments
    clientID: 7da50a3552e40770b2a3
    clientSecret: 9d812e8735398ef87d50ef14a75d62a20b9f6939
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-112779025-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [PHP, HTML, C, JavaScrip, Jquery, Linux, CenOS]
